stages:
  create_experiment:
    cmd: python src/create_experiment.py
    deps:
      - src/create_experiment.py
    outs:
      - experiments/experiment.yaml
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw
    - params.yaml
    - src/preprocess.py
    - experiments/experiment.yaml
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - data/processed
    - params.yaml
    - src/model.py
    - src/train.py
    - experiments/experiment.yaml
    outs:
    - model.pt
    metrics:
    - metrics.json:
        cache: false
  predict:
    cmd: python src/predict.py
    deps:
    - data/processed
    - params.yaml
    - src/model.py
    - src/train.py
    - model.pt
    - experiments/experiment.yaml
